2021-01-06 10:44:52,509 - ERROR - publicLog.py[:52]- Object of type JsonResponse is not JSON serializable
Traceback (most recent call last):
  File "/Volumes/程序员/python_project/lhwms/incoming/views/views.py", line 125, in incoming_search_data
    return restful.ok(data=data)
  File "/Volumes/程序员/python_project/lhwms/lhwms/utils/restful.py", line 28, in ok
    return result(message=message, data=data)
  File "/Volumes/程序员/python_project/lhwms/lhwms/utils/restful.py", line 24, in result
    return JsonResponse(json_data, json_dumps_params={'ensure_ascii': False})
  File "/Users/charlesdeng/workspace/Python_envs/lhwms/lib/python3.9/site-packages/django/http/response.py", line 530, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/charlesdeng/workspace/Python_envs/lhwms/lib/python3.9/site-packages/django/core/serializers/json.py", line 124, in default
    return super(DjangoJSONEncoder, self).default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type JsonResponse is not JSON serializable
2021-01-06 10:51:45,927 - ERROR - publicLog.py[:52]- Object of type JsonResponse is not JSON serializable
Traceback (most recent call last):
  File "/Volumes/程序员/python_project/lhwms/incoming/views/views.py", line 125, in incoming_search_data
    return restful.ok(data=data)
  File "/Volumes/程序员/python_project/lhwms/lhwms/utils/restful.py", line 28, in ok
    return result(message=message, data=data)
  File "/Volumes/程序员/python_project/lhwms/lhwms/utils/restful.py", line 24, in result
    return JsonResponse(json_data, json_dumps_params={'ensure_ascii': False})
  File "/Users/charlesdeng/workspace/Python_envs/lhwms/lib/python3.9/site-packages/django/http/response.py", line 530, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/charlesdeng/workspace/Python_envs/lhwms/lib/python3.9/site-packages/django/core/serializers/json.py", line 124, in default
    return super(DjangoJSONEncoder, self).default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type JsonResponse is not JSON serializable
2021-01-06 10:51:55,390 - ERROR - publicLog.py[:52]- Object of type JsonResponse is not JSON serializable
Traceback (most recent call last):
  File "/Volumes/程序员/python_project/lhwms/incoming/views/views.py", line 125, in incoming_search_data
    return restful.ok(data=data)
  File "/Volumes/程序员/python_project/lhwms/lhwms/utils/restful.py", line 28, in ok
    return result(message=message, data=data)
  File "/Volumes/程序员/python_project/lhwms/lhwms/utils/restful.py", line 24, in result
    return JsonResponse(json_data, json_dumps_params={'ensure_ascii': False})
  File "/Users/charlesdeng/workspace/Python_envs/lhwms/lib/python3.9/site-packages/django/http/response.py", line 530, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/charlesdeng/workspace/Python_envs/lhwms/lib/python3.9/site-packages/django/core/serializers/json.py", line 124, in default
    return super(DjangoJSONEncoder, self).default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type JsonResponse is not JSON serializable
2021-01-06 10:59:44,601 - WARNING - publicLog.py[:58]- Traceback (most recent call last):
  File "/Volumes/程序员/python_project/lhwms/lhwms/utils/data_search.py", line 90, in data_paginator
    current_page_data = paginator.page(page)  # 获取当前页数据对象
  File "/Users/charlesdeng/workspace/Python_envs/lhwms/lib/python3.9/site-packages/django/core/paginator.py", line 57, in page
    number = self.validate_number(number)
  File "/Users/charlesdeng/workspace/Python_envs/lhwms/lib/python3.9/site-packages/django/core/paginator.py", line 50, in validate_number
    raise EmptyPage(_('That page contains no results'))
django.core.paginator.EmptyPage: 本页结果未空

2021-01-06 15:13:45,612 - ERROR - publicLog.py[:52]- Object of type JsonResponse is not JSON serializable
Traceback (most recent call last):
  File "/Volumes/程序员/python_project/lhwms/incoming/views/views.py", line 125, in incoming_search_data
    return restful.ok(data=data)
  File "/Volumes/程序员/python_project/lhwms/lhwms/utils/restful.py", line 28, in ok
    return result(message=message, data=data)
  File "/Volumes/程序员/python_project/lhwms/lhwms/utils/restful.py", line 24, in result
    return JsonResponse(json_data, json_dumps_params={'ensure_ascii': False})
  File "/Users/charlesdeng/workspace/Python_envs/lhwms/lib/python3.9/site-packages/django/http/response.py", line 530, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/charlesdeng/workspace/Python_envs/lhwms/lib/python3.9/site-packages/django/core/serializers/json.py", line 124, in default
    return super(DjangoJSONEncoder, self).default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type JsonResponse is not JSON serializable
2021-01-06 15:17:35,157 - ERROR - publicLog.py[:52]- Object of type JsonResponse is not JSON serializable
Traceback (most recent call last):
  File "/Volumes/程序员/python_project/lhwms/incoming/views/views.py", line 125, in incoming_search_data
    return restful.ok(data=data)
  File "/Volumes/程序员/python_project/lhwms/lhwms/utils/restful.py", line 28, in ok
    return result(message=message, data=data)
  File "/Volumes/程序员/python_project/lhwms/lhwms/utils/restful.py", line 24, in result
    return JsonResponse(json_data, json_dumps_params={'ensure_ascii': False})
  File "/Users/charlesdeng/workspace/Python_envs/lhwms/lib/python3.9/site-packages/django/http/response.py", line 530, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/charlesdeng/workspace/Python_envs/lhwms/lib/python3.9/site-packages/django/core/serializers/json.py", line 124, in default
    return super(DjangoJSONEncoder, self).default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type JsonResponse is not JSON serializable
2021-01-06 15:18:55,338 - WARNING - publicLog.py[:58]- Traceback (most recent call last):
  File "/Volumes/程序员/python_project/lhwms/lhwms/utils/data_search.py", line 90, in data_paginator
    current_page_data = paginator.page(page)  # 获取当前页数据对象
  File "/Users/charlesdeng/workspace/Python_envs/lhwms/lib/python3.9/site-packages/django/core/paginator.py", line 57, in page
    number = self.validate_number(number)
  File "/Users/charlesdeng/workspace/Python_envs/lhwms/lib/python3.9/site-packages/django/core/paginator.py", line 50, in validate_number
    raise EmptyPage(_('That page contains no results'))
django.core.paginator.EmptyPage: 本页结果未空

2021-01-06 15:22:26,672 - ERROR - publicLog.py[:52]- Object of type JsonResponse is not JSON serializable
Traceback (most recent call last):
  File "/Volumes/程序员/python_project/lhwms/incoming/views/views.py", line 125, in incoming_search_data
    return restful.ok(data=data)
  File "/Volumes/程序员/python_project/lhwms/lhwms/utils/restful.py", line 28, in ok
    return result(message=message, data=data)
  File "/Volumes/程序员/python_project/lhwms/lhwms/utils/restful.py", line 24, in result
    return JsonResponse(json_data, json_dumps_params={'ensure_ascii': False})
  File "/Users/charlesdeng/workspace/Python_envs/lhwms/lib/python3.9/site-packages/django/http/response.py", line 530, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/charlesdeng/workspace/Python_envs/lhwms/lib/python3.9/site-packages/django/core/serializers/json.py", line 124, in default
    return super(DjangoJSONEncoder, self).default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type JsonResponse is not JSON serializable
2021-01-06 15:26:59,002 - ERROR - publicLog.py[:52]- Object of type JsonResponse is not JSON serializable
Traceback (most recent call last):
  File "/Volumes/程序员/python_project/lhwms/incoming/views/views.py", line 125, in incoming_search_data
    return restful.ok(data=data)
  File "/Volumes/程序员/python_project/lhwms/lhwms/utils/restful.py", line 28, in ok
    return result(message=message, data=data)
  File "/Volumes/程序员/python_project/lhwms/lhwms/utils/restful.py", line 24, in result
    return JsonResponse(json_data, json_dumps_params={'ensure_ascii': False})
  File "/Users/charlesdeng/workspace/Python_envs/lhwms/lib/python3.9/site-packages/django/http/response.py", line 530, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/charlesdeng/workspace/Python_envs/lhwms/lib/python3.9/site-packages/django/core/serializers/json.py", line 124, in default
    return super(DjangoJSONEncoder, self).default(o)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type JsonResponse is not JSON serializable
